swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Manipulation des transactions
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v2
schemes:
  - https
paths:
#Route pour récupérer les transactions par compte et par mois.
/user/accounts/{accountID}/transactions/currentMonth:
  get:
    security:
      - Bearer: []
    tags:
      - Transactions Module
    summary: User Account API
    description: Returns all transactions for the current month, grouped by account
    produces:
      - application/json
    parameters:
      - in: path
        name: accountID
        description: User account ID
        required: true
        type: integer
        format: int64
      - in: query
        name: startDate
        description: Start date for which transactions must be extracted (format : YYYY-MM-DD)
        required: false
        type: string
        format: date
      - in: query
        name: endDate
        description: End date for which transactions must be extracted (format : YYYY-MM-DD)
        required: false
        type: string
        format: date
    responses:
      '200':
        description: Success, returns transactions grouped by account for the current month
        schema:
          type: object
          properties:
            transactions:
              type: array
              items:
                $ref: '#/definitions/TransactionGroupedByAccount'
      '400':
        description: Invalid query, incorrect month format or missing parameters
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Invalid or missing parameters"
      '401':
        description: Unauthorized, the user is not authenticated or lacks authorization
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Unauthorized - Please login to access this resource"
      '404':
        description: No transactions found for the current month and the specified user
        schema:
          type: object
          properties:
            error:
              type: string
              example: "No transactions found for the current month and the specified user"
      '500':
        description: Internal Server Error
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Internal server error, please try again later"

#Route pour ajouter, modifier ou supprimer des informations sur une transaction
/user/accounts/{accountID}/transactions/{transactionsID}:
  parameters:
    - in: path
      name: accountID
      description: User account ID
      required: true
      type: integer
      format: int64
    - in: path
      name: transactionID
      description: Account transaction ID
      required: true
      type: integer
      format: int64
  ##Visualiser les détails d'une transaction
  get:
    security:
      - Bearer: []
    tags:
      - Transactions Module
    summary: View transaction details
    description: Retrieves the details of a specific transaction
    responses:
      '200':
        description: Success, returns the details of the requested transaction
        schema:
          type: object
          properties:
            transactions:
              type: array
              items:
                $ref: '#/definitions/Transaction'
      '400':
        description: Invalid query
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Invalid or missing parameters"
      '401':
        description: Unauthorized, the user is not authenticated or lacks authorization
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Unauthorized - Please login to access this resource"
      '404':
        description: No transactions found for the specified user
        schema:
          type: object
          properties:
            error:
              type: string
              example: "No transactions found for the specified user"
      '500':
        description: Internal Server Error
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Internal server error, please try again later"
  ##Mettre à jour les détails d'une transaction
  put:
    summary: Update transaction information
    description: Updates the information in an existing transaction
    security:
      - Bearer: []
    tags:
      - Transactions Module
    parameters:
      - in: body
        name: transaction
        description: The new transaction information
        schema:
          $ref: '#/definitions/Transaction'
    responses:
      '200':
        description: Success, transaction updated successfully
        schema:
          type: object
          properties:
            transactions:
              type: array
              items:
                $ref: '#/definitions/Transaction'
      '400':
        description: Invalid request, missing or incorrect transaction data
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Invalid transaction data"
      '401':
        description: Unauthorized, the user is not authenticated or lacks authorization
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Unauthorized - Please login to access this resource"
      '404':
        description: No transactions found for the specified user
        schema:
          type: object
          properties:
            error:
              type: string
              example: "No transactions found for the specified user"
      '500':
        description: Internal Server Error
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Internal server error, please try again later"
  ##Ajouter 
  post:
    security:
      - Bearer: []
    tags:
      - Transactions Module
    summary: Add a new transaction
    description: Adds a new transaction
    parameters:
      - in: body
        name: transaction
        description: The information of the new transaction
        schema:
          $ref: '#/definitions/Transaction'
    responses:
      '201':
        description: Success, transaction added successfully
        schema:
          type: object
          properties:
            transactions:
              type: array
              items:
                $ref: '#/definitions/Transaction'
      '400':
        description: Invalid request, missing or incorrect transaction data
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Invalid transaction data"
      '401':
        description: Unauthorized, the user is not authenticated or lacks authorization
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Unauthorized - Please login to access this resource"
      '404':
        description: No transactions found for the specified user
        schema:
          type: object
          properties:
            error:
              type: string
              example: "No transactions found for the specified user"
      '500':
        description: Internal Server Error
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Internal server error, please try again later"
  ##Supprimer
  delete:
    summary: Delete a transaction
    description: Deletes an existing transaction
    security:
      - Bearer: []
    tags:
      - Transactions Module
    responses:
      '204':
        description: Success, transaction deleted successfully
        schema:
          type: object
          properties:
            transactions:
              type: array
              items:
                $ref: '#/definitions/Transaction'
      '400':
        description: Invalid query
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Invalid or missing parameters"
      '401':
        description: Unauthorized, the user is not authenticated or lacks authorization
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Unauthorized - Please login to access this resource"
      '404':
        description: No transactions found for the specified user
        schema:
          type: object
          properties:
            error:
              type: string
              example: "No transactions found for the specified user"
      '500':
        description: Internal Server Error
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Internal server error, please try again later"

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Transaction ID
      accountId:
        type: integer
        description: ID of the account associated with the transaction
      amount:
        type: number
        description: Transaction amount
      date:
        type: string
        format: date-time
        description: Transaction date and time
      description:
        type: string
        description: Transaction description
  TransactionGroupedByAccount:
    type: object
    properties:
      accountId:
        type: integer
        description: ID of the account
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  TransactionForModification:
    type: object
    properties:
      accountId:
        type: integer
        description: ID of the account associated with the transaction
      amount:
        type: number
        description: Transaction amount
      date:
        type: string
        format: date-time
        description: Transaction date and time
      description:
        type: string
        description: Transaction description
  TransactionForAddition:
    type: object
    properties:
      accountId:
        type: integer
        description: ID of the account associated with the transaction
      amount:
        type: number
        description: Transaction amount
      date:
        type: string
        format: date-time
        description: Transaction date and time
      description:
        type: string
        description: Transaction description
  TransactionForDeletion:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: ID of the transaction to delete 
